//@provengo summon rest
//@provengo summon rtv
// Generated by generator_v56 context-generate; do not edit.
var svc = new RESTSession("http://127.0.0.1:59042", "context-client", {headers:{"Content-Type":"application/json"}});

// Native REST events, matching the attached Library interface pattern.
// Metadata is local to the model; it is NOT sent as URL query parameters.
function requestBodyExpression(value) {
    // Resolve references and serialize JSON together at actuation, in ONE RTV phrase.
    // Never interpolate several RTV phrases into an already serialized nested JSON body.
    function source(v) {
        if(typeof v==="string" && /^@\{[A-Za-z0-9_]+\}$/.test(v)) return v.slice(2,-1);
        if(Array.isArray(v)) return "["+v.map(source).join(",")+"]";
        if(v && typeof v==="object") return "{"+Object.keys(v).map(function(k){return JSON.stringify(k)+":"+source(v[k]);}).join(",")+"}";
        return JSON.stringify(v);
    }
    return "@{JSON.stringify("+source(value)+")}";
}
function requestRest(method, url, body, codes, semantic, callback) {
    var data = {
        lib: "REST", method: method, url: svc.baseURL + url,
        headers: svc.defaultHeaders, parameters: {},
        expectedResponseCodes: codes, callback: callback, model: semantic
    };
    if (body !== undefined) data.body = typeof body === "string" ? body : requestBodyExpression(body);
    return sync({request: bp.Event(method, data)});
}
function matchesInterfaceEvent(action, type, logicalId) {
    return bp.EventSet(action + ":" + type + ":" + logicalId, function(event) {
        var m = event.data && event.data.model;
        return !!m && m.action === action && m.type === type &&
            (logicalId === undefined || m.logicalId === logicalId);
    });
}
function extractEventData(event) {
    return event.data && event.data.model;
}
function matchesVerified(logicalId, revision) {
    return bp.EventSet("Verified " + logicalId + "/" + revision, function(event) {
        return event.name === "ModelVerified" && event.data.logicalId === logicalId && event.data.revision === revision;
    });
}
function matchesMutations(logicalId) {
    return bp.EventSet("Writes " + logicalId, function(event) {
        var m = event.data && event.data.model;
        return !!m && m.logicalId === logicalId && (m.action === "create" || m.action === "update");
    });
}
function matchesConflictingWrites(resourceId, owner) {
    return bp.EventSet("Conflicting write "+resourceId,function(event){
        var m=event.data && event.data.model;
        if(event.name==="ModelWriteBegin") return event.data.logicalId===resourceId && event.data.owner!==owner;
        return !!m && m.owner!==owner && (m.action==="create" || m.action==="update") &&
            (m.affected || [m.logicalId]).indexOf(resourceId)>=0;
    });
}
function callbackFromSource(source) {
    // Capture arguments in source literals: callbacks run at actuation, after sampling.
    return new Function("response", source);
}
function validationSource(expected, identityKey, snapshotKey, prepare, bindIdentity) {
    return "var expected = " + JSON.stringify(expected) + ";\n" +
        "function resolve(v) { if(typeof v === 'string' && /^@\\{[A-Za-z0-9_]+\\}$/.test(v)) return pvg.rtv.get(v.slice(2,-1)); if(Array.isArray(v)) return v.map(resolve); if(v && typeof v === 'object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}\n" +
        "expected = resolve(expected);\n" +
        "function check(actual,wanted,path) { if(Array.isArray(wanted)){if(!Array.isArray(actual)||actual.length!==wanted.length) {pvg.fail('Array mismatch '+path);return;} wanted.forEach(function(v,i){check(actual[i],v,path+'['+i+']');});} else if(wanted && typeof wanted === 'object'){ if(!actual||typeof actual!=='object'){pvg.fail('Object mismatch '+path);return;} Object.keys(wanted).forEach(function(k){check(actual[k],wanted[k],path+'.'+k);});} else if(actual!==wanted){pvg.fail('Value mismatch '+path+': expected '+JSON.stringify(wanted)+' observed '+JSON.stringify(actual));}}\n" +
        "var actual=JSON.parse(response.body); check(actual,expected,'$');\n" +
        (identityKey ? ("if(!actual || !actual.id){pvg.fail('Readback identity absent');return;}" +
            (bindIdentity ? "" : "var known=pvg.rtv.get(" + JSON.stringify(identityKey) + ");if(String(actual.id)!==String(known)){pvg.fail('Stable identity changed');return;}") +
            "pvg.rtv.set(" + JSON.stringify(identityKey) + ",actual.id);\n") : "") +
        (snapshotKey ? "pvg.rtv.set(" + JSON.stringify(snapshotKey) + ",response.body);\n" : "") +
        (prepare || "");
}


// #/paths/~1resources/post
var AnyFixtureResourceCreated = matchesInterfaceEvent("create","FixtureResource");
var AnyFixtureResourceUpdated = matchesInterfaceEvent("update","FixtureResource");
function createFixtureResource(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/resources",body,[201],
        {action:"create",type:"FixtureResource",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1resources~1{id}/get
function verifyFixtureResource(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/resources/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"FixtureResource",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1resources~1{id}/patch
function updateFixtureResource(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"name\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"name\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/resources/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"FixtureResource",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PATCH","/resources/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"FixtureResource",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}


// HTTP transport collection is separate from contract classification.
function observedResponseCodes(declared) {
    var codes=declared.slice();
    for(var code=400;code<=599;code++) if(codes.indexOf(code)<0) codes.push(code);
    return codes;
}
function requestObservedRest(method,url,body,declared,id,targets) {
    if(!targets.length) throw new Error('Observation needs identity-bound readbacks');
    sync({request:bp.Event('ObservationBegin',{id:id,targets:targets})});
    var source='var raw=response||{};var r={code:raw.code,body:raw.body,captureComplete:typeof raw.code==="number" && raw.code%1===0 && raw.code>=100 && raw.code<=599,contractStatusValid:'+JSON.stringify(declared)+'.indexOf(raw.code)>=0};';
    source+='pvg.rtv.set('+JSON.stringify('OBS_'+id)+',JSON.stringify(r));';
    requestRest(method,url,body,observedResponseCodes(declared),
        {action:'observe',observationId:id},callbackFromSource(source));
    sync({request:bp.Event('ObservationReady',{id:id})});
}
function readObservedTarget(observation,target,index) {
    var source='var key='+JSON.stringify('OBS_'+observation.id)+';';
    source+='var record=JSON.parse(pvg.rtv.get(key));';
    source+='record.readbacks=record.readbacks||[];';
    source+='var target='+JSON.stringify(target)+';';
    source+='var read={logicalId:target.logicalId,code:response.code,usable:false};';
    source+='try{var payload=JSON.parse(response.body);read.actual=payload;';
    source+='read.identityMatches=payload[target.identityField]!==undefined && pvg.rtv.get(target.identityKey)!==undefined && String(payload[target.identityField])===String(pvg.rtv.get(target.identityKey));';
    source+='function resolve(v){if(typeof v==="string"){var m=/^@\\{([A-Za-z0-9_]+)\\}$/.exec(v);return m?pvg.rtv.get(m[1]):v;}if(Array.isArray(v))return v.map(resolve);if(v && typeof v==="object"){var out={};Object.keys(v).forEach(function(k){out[k]=resolve(v[k]);});return out;}return v;}target.expected=resolve(target.expected);';
    source+='read.expectedMatches=Object.keys(target.expected).every(function(k){return JSON.stringify(payload[k])===JSON.stringify(target.expected[k]);});';
    source+='read.usable=target.codes.indexOf(response.code)>=0 && read.identityMatches;';
    source+='}catch(error){read.decodeError=String(error);}';
    source+='record.readbacks['+index+']=read;pvg.rtv.set(key,JSON.stringify(record));';
    if(index===observation.targets.length-1) {
        source+='record.observationsComplete=record.captureComplete && record.readbacks.length==='+observation.targets.length+' && record.readbacks.every(function(r){return !!r && r.usable;});';
        source+='pvg.rtv.set(key,JSON.stringify(record));bp.log.info("OBSERVATION_EVIDENCE "+JSON.stringify(record));';
        source+='if(!record.observationsComplete || !record.contractStatusValid) pvg.fail("Observation incomplete or contract failure after readbacks");';
    }
    return requestRest('GET',target.url,undefined,observedResponseCodes(target.codes),
        {action:'observationReadback',observationId:observation.id},callbackFromSource(source));
}


// Fixture-only process binding: expected state is the verified central DAL resource.
function observeFixtureResource(resource) {
    bp.log.info('OBSERVATION_MODEL '+JSON.stringify(resource.expected));
    var targets=[{logicalId:resource.id,expected:cloneExpected(resource.expected),
        identityField:"id",identityKey:"ID_FixtureResource_1",url:"/resources/@{ROUTE_FixtureResource_1}",codes:[200]}];
    requestObservedRest('POST',"/resources/@{ROUTE_FixtureResource_1}/action",{},[200],'fixture-observation',targets);
}
