"""Fixture-only process driver, layered on the actual central CLI output."""
import hashlib,json,sys
from pathlib import Path

def compile_driver(generator_root,contract,js):
    sys.path.insert(0,str(Path(generator_root).resolve()))
    from generator_v56.render.context_model import build_model, j
    raw=json.loads(Path(contract).read_text());c,entities=build_model(raw,['/resources'],1,20261007)
    if len(entities)!=1:raise ValueError('Fixture must have exactly one entity')
    e=entities[0];logical=e['name']+'_1';key=logical.replace('-','_')
    action_path='/resources/{id}/action'
    action=raw['paths'][action_path]['post'];action_codes,_=c.response(action);read_codes,_=c.response(e['get'])
    iface="""
// Fixture-only process binding: expected state is the verified central DAL resource.
function observeFixtureResource(resource) {
    bp.log.info('OBSERVATION_MODEL '+JSON.stringify(resource.expected));
    var targets=[{logicalId:resource.id,expected:cloneExpected(resource.expected),
        identityField:IDENTITY,identityKey:IDKEY,url:READURL,codes:READCODES}];
    requestObservedRest('POST',ACTIONURL,{},ACTIONCODES,'fixture-observation',targets);
}
"""
    replacements={'IDENTITY':j(e['route_field']),'IDKEY':j('ID_'+key),'READURL':j(e['detail'].replace('{'+e['parameter']+'}','@{ROUTE_'+key+'}')),'READCODES':j(read_codes),'ACTIONURL':j(action_path.replace('{id}','@{ROUTE_'+key+'}')),'ACTIONCODES':j(action_codes)}
    for token,value in replacements.items():iface=iface.replace(token,value)
    stories="\n// Generated fixture process; lifecycle and verifiers remain generated by the central CLI.\nbthread('observe verified fixture',function(){\n    var resource=waitForResource("+j(logical)+",2);\n    observeFixtureResource(resource);\n});\n"
    js=Path(js)
    with (js/'interfaces.fixture.js').open('a',encoding='utf-8',newline='\n') as f:f.write(iface)
    with (js/'stories.fixture.js').open('a',encoding='utf-8',newline='\n') as f:f.write(stories)
    sources={}
    for name in ['generator_v56/cli.py','generator_v56/render/context_model.py','generator_v56/render/context_observation_common.py']:
        sources[name]=hashlib.sha256((Path(generator_root)/name).read_bytes()).hexdigest()
    (js/'fixture-driver-provenance.json').write_text(json.dumps({'fixture_only':True,'central_cli_generated_lifecycle':True,'test_driver_source':'compile_fixture.py','action_source':'#/paths/~1resources~1{id}~1action/post','read_source':e['provenance'],'generator_source_sha256':sources},indent=2))
