//@provengo summon rest
//@provengo summon rtv
// Generated by generator_v56 context-generate; do not edit.
var svc = new RESTSession("http://127.0.0.1:9925", "context-client", {headers:{"Content-Type":"application/json","Authorization":"Bearer @{SBT_AUTH_TOKEN}"}});

// Native REST events, matching the attached Library interface pattern.
// Metadata is local to the model; it is NOT sent as URL query parameters.
function requestBodyExpression(value) {
    // Resolve references and serialize JSON together at actuation, in ONE RTV phrase.
    // Never interpolate several RTV phrases into an already serialized nested JSON body.
    function source(v) {
        if(typeof v==="string" && /^@\{[A-Za-z0-9_]+\}$/.test(v)) return v.slice(2,-1);
        if(Array.isArray(v)) return "["+v.map(source).join(",")+"]";
        if(v && typeof v==="object") return "{"+Object.keys(v).map(function(k){return JSON.stringify(k)+":"+source(v[k]);}).join(",")+"}";
        return JSON.stringify(v);
    }
    return "@{JSON.stringify("+source(value)+")}";
}
function requestRest(method, url, body, codes, semantic, callback) {
    var data = {
        lib: "REST", method: method, url: svc.baseURL + url,
        headers: svc.defaultHeaders, parameters: {},
        expectedResponseCodes: codes, callback: callback, model: semantic
    };
    if (body !== undefined) data.body = typeof body === "string" ? body : requestBodyExpression(body);
    return sync({request: bp.Event(method, data)});
}
function matchesInterfaceEvent(action, type, logicalId) {
    return bp.EventSet(action + ":" + type + ":" + logicalId, function(event) {
        var m = event.data && event.data.model;
        return !!m && m.action === action && m.type === type &&
            (logicalId === undefined || m.logicalId === logicalId);
    });
}
function extractEventData(event) {
    return event.data && event.data.model;
}
function matchesVerified(logicalId, revision) {
    return bp.EventSet("Verified " + logicalId + "/" + revision, function(event) {
        return event.name === "ModelVerified" && event.data.logicalId === logicalId && event.data.revision === revision;
    });
}
function matchesMutations(logicalId) {
    return bp.EventSet("Writes " + logicalId, function(event) {
        var m = event.data && event.data.model;
        return !!m && m.logicalId === logicalId && (m.action === "create" || m.action === "update");
    });
}
function matchesConflictingWrites(resourceId, owner) {
    return bp.EventSet("Conflicting write "+resourceId,function(event){
        var m=event.data && event.data.model;
        if(event.name==="ModelWriteBegin") return event.data.logicalId===resourceId && event.data.owner!==owner;
        return !!m && m.owner!==owner && (m.action==="create" || m.action==="update") &&
            (m.affected || [m.logicalId]).indexOf(resourceId)>=0;
    });
}
function callbackFromSource(source) {
    // Capture arguments in source literals: callbacks run at actuation, after sampling.
    return new Function("response", source);
}
function validationSource(expected, identityKey, snapshotKey, prepare, bindIdentity) {
    return "var expected = " + JSON.stringify(expected) + ";\n" +
        "function resolve(v) { if(typeof v === 'string' && /^@\\{[A-Za-z0-9_]+\\}$/.test(v)) return pvg.rtv.get(v.slice(2,-1)); if(Array.isArray(v)) return v.map(resolve); if(v && typeof v === 'object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}\n" +
        "expected = resolve(expected);\n" +
        "function check(actual,wanted,path) { if(Array.isArray(wanted)){if(!Array.isArray(actual)||actual.length!==wanted.length) {pvg.fail('Array mismatch '+path);return;} wanted.forEach(function(v,i){check(actual[i],v,path+'['+i+']');});} else if(wanted && typeof wanted === 'object'){ if(!actual||typeof actual!=='object'){pvg.fail('Object mismatch '+path);return;} Object.keys(wanted).forEach(function(k){check(actual[k],wanted[k],path+'.'+k);});} else if(actual!==wanted){pvg.fail('Value mismatch '+path+': expected '+JSON.stringify(wanted)+' observed '+JSON.stringify(actual));}}\n" +
        "var actual=JSON.parse(response.body); check(actual,expected,'$');\n" +
        (identityKey ? ("if(!actual || !actual.id){pvg.fail('Readback identity absent');return;}" +
            (bindIdentity ? "" : "var known=pvg.rtv.get(" + JSON.stringify(identityKey) + ");if(String(actual.id)!==String(known)){pvg.fail('Stable identity changed');return;}") +
            "pvg.rtv.set(" + JSON.stringify(identityKey) + ",actual.id);\n") : "") +
        (snapshotKey ? "pvg.rtv.set(" + JSON.stringify(snapshotKey) + ",response.body);\n" : "") +
        (prepare || "");
}

// #/components/securitySchemes/OAuth2PasswordBearer and #/paths/~1api~1auth~1token/post
// Credentials are evaluated from the child-process environment at execution.
// No credential value is included in generated source or symbolic samples.
var AuthenticationReady = bp.Event("AuthenticationReady");
var BusinessHTTP = bp.EventSet("Business HTTP", function(event) {
    return !!(event.data && event.data.lib === "REST" && event.data.model && event.data.model.action !== "authenticate");
});
function authenticate() {
    var callback = callbackFromSource("var token=JSON.parse(response.body);if(typeof token.access_token!=='string'||!token.access_token) {pvg.fail('OAuth2 access_token absent');return;}if(token.token_type && String(token.token_type).toLowerCase()!=='bearer'){pvg.fail('Unsupported OAuth2 token type');return;}pvg.rtv.set('SBT_AUTH_TOKEN',token.access_token);");
    return sync({request:bp.Event("POST", {
        lib:"REST",method:"POST",url:"http://127.0.0.1:9925/api/auth/token",
        headers:{"Content-Type":"application/x-www-form-urlencoded"},parameters:{},
        body:"username=@{encodeURIComponent(java.lang.System.getenv('SBT_USERNAME'))}&password=@{encodeURIComponent(java.lang.System.getenv('SBT_PASSWORD'))}",expectedResponseCodes:[200],
        model:{action:"authenticate"},callback:callback
    })});
}

// #/paths/~1api~1foods/post
var AnyIngredientFoodCreated = matchesInterfaceEvent("create","IngredientFood");
var AnyIngredientFoodUpdated = matchesInterfaceEvent("update","IngredientFood");
function createIngredientFood(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/foods",body,[201],
        {action:"create",type:"IngredientFood",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1foods~1{item_id}/get
function verifyIngredientFood(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/foods/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"IngredientFood",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1foods~1{item_id}/put
function updateIngredientFood(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"id\",\"name\",\"pluralName\",\"description\",\"extras\",\"labelId\",\"aliases\",\"substitutions\",\"householdsWithIngredientFood\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"name\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/foods/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"IngredientFood",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/foods/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"IngredientFood",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

// #/paths/~1api~1units/post
var AnyIngredientUnitCreated = matchesInterfaceEvent("create","IngredientUnit");
var AnyIngredientUnitUpdated = matchesInterfaceEvent("update","IngredientUnit");
function createIngredientUnit(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/units",body,[201],
        {action:"create",type:"IngredientUnit",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1units~1{item_id}/get
function verifyIngredientUnit(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/units/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"IngredientUnit",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1units~1{item_id}/put
function updateIngredientUnit(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"id\",\"name\",\"pluralName\",\"description\",\"extras\",\"fraction\",\"abbreviation\",\"pluralAbbreviation\",\"useAbbreviation\",\"aliases\",\"standardQuantity\",\"standardUnit\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"name\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/units/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"IngredientUnit",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/units/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"IngredientUnit",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

// #/paths/~1api~1recipes/post
var AnyRecipeCreated = matchesInterfaceEvent("create","Recipe");
var AnyRecipeUpdated = matchesInterfaceEvent("update","Recipe");
function createRecipe(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(typeof payload!=='string'||!payload) pvg.fail('No route locator');pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload);\n";
    return requestRest("POST","/api/recipes",body,[201],
        {action:"create",type:"Recipe",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1recipes~1{slug}/get
function verifyRecipe(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/recipes/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"Recipe",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,resource.revision===1 && resource.verifiedRevision===0)));
}

// #/paths/~1api~1recipes~1{slug}/patch
function updateRecipe(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"id\",\"userId\",\"householdId\",\"groupId\",\"name\",\"slug\",\"image\",\"recipeServings\",\"recipeYieldQuantity\",\"recipeYield\",\"totalTime\",\"prepTime\",\"cookTime\",\"performTime\",\"description\",\"recipeCategory\",\"tags\",\"tools\",\"rating\",\"orgURL\",\"dateAdded\",\"dateUpdated\",\"createdAt\",\"update_at\",\"lastMade\",\"recipeIngredient\",\"recipeInstructions\",\"nutrition\",\"settings\",\"assets\",\"notes\",\"extras\",\"comments\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/recipes/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"Recipe",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PATCH","/api/recipes/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"Recipe",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

function linkRecipeDependencies(resource, parents) {
    var links=[];
    var item0={"quantity":1};
    var dependency0unit={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency0unit[f]=parents["IngredientUnit"].expected[f];});
    dependency0unit.id="@{ID_"+parents["IngredientUnit"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item0["unit"]=dependency0unit;
    var dependency0food={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency0food[f]=parents["IngredientFood"].expected[f];});
    dependency0food.id="@{ID_"+parents["IngredientFood"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item0["food"]=dependency0food;
    links.push(item0);
    var item1={"quantity":1};
    var dependency1unit={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency1unit[f]=parents["IngredientUnit"].expected[f];});
    dependency1unit.id="@{ID_"+parents["IngredientUnit"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item1["unit"]=dependency1unit;
    var dependency1food={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency1food[f]=parents["IngredientFood"].expected[f];});
    dependency1food.id="@{ID_"+parents["IngredientFood"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item1["food"]=dependency1food;
    links.push(item1);
    var delta={}; delta["recipeIngredient"]=links;
    updateRecipe(resource,delta);
}

// #/paths/~1api~1households~1shopping~1lists/post
var AnyShoppingListOutCreated = matchesInterfaceEvent("create","ShoppingListOut");
var AnyShoppingListOutUpdated = matchesInterfaceEvent("update","ShoppingListOut");
function createShoppingListOut(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/households/shopping/lists",body,[201],
        {action:"create",type:"ShoppingListOut",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1households~1shopping~1lists~1{item_id}/get
function verifyShoppingListOut(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/households/shopping/lists/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"ShoppingListOut",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1households~1shopping~1lists~1{item_id}/put
function updateShoppingListOut(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"name\",\"extras\",\"createdAt\",\"update_at\",\"groupId\",\"userId\",\"id\",\"listItems\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"groupId\",\"userId\",\"id\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/households/shopping/lists/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"ShoppingListOut",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/households/shopping/lists/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"ShoppingListOut",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

// #/paths/~1api~1households~1shopping~1items/post
var AnyShoppingListItemOutCreated = matchesInterfaceEvent("create","ShoppingListItemOut");
var AnyShoppingListItemOutUpdated = matchesInterfaceEvent("update","ShoppingListItemOut");
function createShoppingListItemOut(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    body["shoppingListId"]="@{ID_" + parents["ShoppingListOut"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    body["foodId"]="@{ID_" + parents["IngredientFood"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    body["unitId"]="@{ID_" + parents["IngredientUnit"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    body["recipeReferences"]=[{"recipeQuantity":1,"recipeScale":1}];
    body["recipeReferences"][0]["recipeId"]="@{ID_" + parents["Recipe"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "var candidates=[];";
    source += "var fields=[\"createdItems\",\"updatedItems\",\"deletedItems\"];fields.forEach(function(f){(payload[f]||[]).forEach(function(item){candidates.push(item);});});";
    source += "if(candidates.length!==1) pvg.fail('Create identity ambiguous; no merge guess');payload=candidates[0];\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/households/shopping/items",body,[201],
        {action:"create",type:"ShoppingListItemOut",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1households~1shopping~1items~1{item_id}/get
function verifyShoppingListItemOut(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/households/shopping/items/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"ShoppingListItemOut",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1households~1shopping~1items~1{item_id}/put
function updateShoppingListItemOut(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"quantity\",\"unit\",\"food\",\"referencedRecipe\",\"note\",\"display\",\"shoppingListId\",\"checked\",\"position\",\"foodId\",\"labelId\",\"unitId\",\"extras\",\"recipeReferences\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"shoppingListId\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/households/shopping/items/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"ShoppingListItemOut",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/households/shopping/items/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"ShoppingListItemOut",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}
