//@provengo summon rest
//@provengo summon rtv
// Generated by generator_v56 context-generate; do not edit.
var svc = new RESTSession("http://127.0.0.1:9925", "context-client", {headers:{"Content-Type":"application/json","Authorization":"Bearer @{SBT_AUTH_TOKEN}"}});

// Native REST events, matching the attached Library interface pattern.
// Metadata is local to the model; it is NOT sent as URL query parameters.
function requestBodyExpression(value) {
    // Resolve references and serialize JSON together at actuation, in ONE RTV phrase.
    // Never interpolate several RTV phrases into an already serialized nested JSON body.
    function source(v) {
        if(typeof v==="string" && /^@\{[A-Za-z0-9_]+\}$/.test(v)) return v.slice(2,-1);
        if(Array.isArray(v)) return "["+v.map(source).join(",")+"]";
        if(v && typeof v==="object") return "{"+Object.keys(v).map(function(k){return JSON.stringify(k)+":"+source(v[k]);}).join(",")+"}";
        return JSON.stringify(v);
    }
    return "@{JSON.stringify("+source(value)+")}";
}
function requestRest(method, url, body, codes, semantic, callback) {
    var data = {
        lib: "REST", method: method, url: svc.baseURL + url,
        headers: svc.defaultHeaders, parameters: {},
        expectedResponseCodes: codes, callback: callback, model: semantic
    };
    if (body !== undefined) data.body = typeof body === "string" ? body : requestBodyExpression(body);
    return sync({request: bp.Event(method, data)});
}
function matchesInterfaceEvent(action, type, logicalId) {
    return bp.EventSet(action + ":" + type + ":" + logicalId, function(event) {
        var m = event.data && event.data.model;
        return !!m && m.action === action && m.type === type &&
            (logicalId === undefined || m.logicalId === logicalId);
    });
}
function extractEventData(event) {
    return event.data && event.data.model;
}
function matchesVerified(logicalId, revision) {
    return bp.EventSet("Verified " + logicalId + "/" + revision, function(event) {
        return event.name === "ModelVerified" && event.data.logicalId === logicalId && event.data.revision === revision;
    });
}
function matchesMutations(logicalId) {
    return bp.EventSet("Writes " + logicalId, function(event) {
        var m = event.data && event.data.model;
        return !!m && m.logicalId === logicalId && (m.action === "create" || m.action === "update");
    });
}
function matchesConflictingWrites(resourceId, owner) {
    return bp.EventSet("Conflicting write "+resourceId,function(event){
        var m=event.data && event.data.model;
        if(event.name==="ModelWriteBegin") return event.data.logicalId===resourceId && event.data.owner!==owner;
        return !!m && m.owner!==owner && (m.action==="create" || m.action==="update") &&
            (m.affected || [m.logicalId]).indexOf(resourceId)>=0;
    });
}
function callbackFromSource(source) {
    // Capture arguments in source literals: callbacks run at actuation, after sampling.
    return new Function("response", source);
}
function validationSource(expected, identityKey, snapshotKey, prepare, bindIdentity) {
    return "var expected = " + JSON.stringify(expected) + ";\n" +
        "function resolve(v) { if(typeof v === 'string' && /^@\\{[A-Za-z0-9_]+\\}$/.test(v)) return pvg.rtv.get(v.slice(2,-1)); if(Array.isArray(v)) return v.map(resolve); if(v && typeof v === 'object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}\n" +
        "expected = resolve(expected);\n" +
        "function check(actual,wanted,path) { if(Array.isArray(wanted)){if(!Array.isArray(actual)||actual.length!==wanted.length) {pvg.fail('Array mismatch '+path);return;} wanted.forEach(function(v,i){check(actual[i],v,path+'['+i+']');});} else if(wanted && typeof wanted === 'object'){ if(!actual||typeof actual!=='object'){pvg.fail('Object mismatch '+path);return;} Object.keys(wanted).forEach(function(k){check(actual[k],wanted[k],path+'.'+k);});} else if(actual!==wanted){pvg.fail('Value mismatch '+path+': expected '+JSON.stringify(wanted)+' observed '+JSON.stringify(actual));}}\n" +
        "var actual=JSON.parse(response.body); check(actual,expected,'$');\n" +
        (identityKey ? ("if(!actual || !actual.id){pvg.fail('Readback identity absent');return;}" +
            (bindIdentity ? "" : "var known=pvg.rtv.get(" + JSON.stringify(identityKey) + ");if(String(actual.id)!==String(known)){pvg.fail('Stable identity changed');return;}") +
            "pvg.rtv.set(" + JSON.stringify(identityKey) + ",actual.id);\n") : "") +
        (snapshotKey ? "pvg.rtv.set(" + JSON.stringify(snapshotKey) + ",response.body);\n" : "") +
        (prepare || "");
}

// #/components/securitySchemes/OAuth2PasswordBearer and #/paths/~1api~1auth~1token/post
// Credentials are evaluated from the child-process environment at execution.
// No credential value is included in generated source or symbolic samples.
var AuthenticationReady = bp.Event("AuthenticationReady");
var BusinessHTTP = bp.EventSet("Business HTTP", function(event) {
    return !!(event.data && event.data.lib === "REST" && event.data.model && event.data.model.action !== "authenticate");
});
function authenticate() {
    var callback = callbackFromSource("var token=JSON.parse(response.body);if(typeof token.access_token!=='string'||!token.access_token) {pvg.fail('OAuth2 access_token absent');return;}if(token.token_type && String(token.token_type).toLowerCase()!=='bearer'){pvg.fail('Unsupported OAuth2 token type');return;}pvg.rtv.set('SBT_AUTH_TOKEN',token.access_token);");
    return sync({request:bp.Event("POST", {
        lib:"REST",method:"POST",url:"http://127.0.0.1:9925/api/auth/token",
        headers:{"Content-Type":"application/x-www-form-urlencoded"},parameters:{},
        body:"username=@{encodeURIComponent(java.lang.System.getenv('SBT_USERNAME'))}&password=@{encodeURIComponent(java.lang.System.getenv('SBT_PASSWORD'))}",expectedResponseCodes:[200],
        model:{action:"authenticate"},callback:callback
    })});
}

// #/paths/~1api~1foods/post
var AnyIngredientFoodCreated = matchesInterfaceEvent("create","IngredientFood");
var AnyIngredientFoodUpdated = matchesInterfaceEvent("update","IngredientFood");
function createIngredientFood(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/foods",body,[201],
        {action:"create",type:"IngredientFood",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1foods~1{item_id}/get
function verifyIngredientFood(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/foods/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"IngredientFood",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1foods~1{item_id}/put
function updateIngredientFood(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"id\",\"name\",\"pluralName\",\"description\",\"extras\",\"labelId\",\"aliases\",\"substitutions\",\"householdsWithIngredientFood\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"name\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/foods/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"IngredientFood",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/foods/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"IngredientFood",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

// #/paths/~1api~1units/post
var AnyIngredientUnitCreated = matchesInterfaceEvent("create","IngredientUnit");
var AnyIngredientUnitUpdated = matchesInterfaceEvent("update","IngredientUnit");
function createIngredientUnit(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/units",body,[201],
        {action:"create",type:"IngredientUnit",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1units~1{item_id}/get
function verifyIngredientUnit(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/units/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"IngredientUnit",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1units~1{item_id}/put
function updateIngredientUnit(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"id\",\"name\",\"pluralName\",\"description\",\"extras\",\"fraction\",\"abbreviation\",\"pluralAbbreviation\",\"useAbbreviation\",\"aliases\",\"standardQuantity\",\"standardUnit\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"name\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/units/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"IngredientUnit",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/units/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"IngredientUnit",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

// #/paths/~1api~1recipes/post
var AnyRecipeCreated = matchesInterfaceEvent("create","Recipe");
var AnyRecipeUpdated = matchesInterfaceEvent("update","Recipe");
function createRecipe(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(typeof payload!=='string'||!payload) pvg.fail('No route locator');pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload);\n";
    return requestRest("POST","/api/recipes",body,[201],
        {action:"create",type:"Recipe",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1recipes~1{slug}/get
function verifyRecipe(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/recipes/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"Recipe",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,resource.revision===1 && resource.verifiedRevision===0)));
}

// #/paths/~1api~1recipes~1{slug}/patch
function updateRecipe(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"id\",\"userId\",\"householdId\",\"groupId\",\"name\",\"slug\",\"image\",\"recipeServings\",\"recipeYieldQuantity\",\"recipeYield\",\"totalTime\",\"prepTime\",\"cookTime\",\"performTime\",\"description\",\"recipeCategory\",\"tags\",\"tools\",\"rating\",\"orgURL\",\"dateAdded\",\"dateUpdated\",\"createdAt\",\"update_at\",\"lastMade\",\"recipeIngredient\",\"recipeInstructions\",\"nutrition\",\"settings\",\"assets\",\"notes\",\"extras\",\"comments\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/recipes/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"Recipe",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PATCH","/api/recipes/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"Recipe",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

function linkRecipeDependencies(resource, parents) {
    var links=[];
    var item0={"quantity":2};
    var dependency0unit={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency0unit[f]=parents["IngredientUnit"].expected[f];});
    dependency0unit.id="@{ID_"+parents["IngredientUnit"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item0["unit"]=dependency0unit;
    var dependency0food={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency0food[f]=parents["IngredientFood"].expected[f];});
    dependency0food.id="@{ID_"+parents["IngredientFood"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item0["food"]=dependency0food;
    links.push(item0);
    var item1={"quantity":4};
    var dependency1unit={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency1unit[f]=parents["IngredientUnit"].expected[f];});
    dependency1unit.id="@{ID_"+parents["IngredientUnit"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item1["unit"]=dependency1unit;
    var dependency1food={};
    ["id","name"].forEach(function(f){if(f!=="id") dependency1food[f]=parents["IngredientFood"].expected[f];});
    dependency1food.id="@{ID_"+parents["IngredientFood"].id.replace(/[^A-Za-z0-9_]/g,"_")+"}";
    item1["food"]=dependency1food;
    links.push(item1);
    var delta={}; delta["recipeIngredient"]=links;
    delta["recipeServings"]=1;
    delta["recipeYieldQuantity"]=1;
    delta["rating"]=1;
    updateRecipe(resource,delta);
}

// #/paths/~1api~1households~1shopping~1lists/post
var AnyShoppingListOutCreated = matchesInterfaceEvent("create","ShoppingListOut");
var AnyShoppingListOutUpdated = matchesInterfaceEvent("update","ShoppingListOut");
function createShoppingListOut(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/households/shopping/lists",body,[201],
        {action:"create",type:"ShoppingListOut",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1households~1shopping~1lists~1{item_id}/get
function verifyShoppingListOut(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/households/shopping/lists/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"ShoppingListOut",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1households~1shopping~1lists~1{item_id}/put
function updateShoppingListOut(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"name\",\"extras\",\"createdAt\",\"update_at\",\"groupId\",\"userId\",\"id\",\"listItems\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"groupId\",\"userId\",\"id\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/households/shopping/lists/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"ShoppingListOut",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/households/shopping/lists/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"ShoppingListOut",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

// #/paths/~1api~1households~1shopping~1items/post
var AnyShoppingListItemOutCreated = matchesInterfaceEvent("create","ShoppingListItemOut");
var AnyShoppingListItemOutUpdated = matchesInterfaceEvent("update","ShoppingListItemOut");
function createShoppingListItemOut(logicalId, fixture, parents) {
    var body=JSON.parse(JSON.stringify(fixture));
    body["shoppingListId"]="@{ID_" + parents["ShoppingListOut"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    body["foodId"]="@{ID_" + parents["IngredientFood"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    body["unitId"]="@{ID_" + parents["IngredientUnit"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    body["recipeReferences"]=[{"recipeQuantity":1,"recipeScale":1}];
    body["recipeReferences"][0]["recipeId"]="@{ID_" + parents["Recipe"].id.replace(/[^A-Za-z0-9_]/g,"_") + "}";
    var key=logicalId.replace(/[^A-Za-z0-9_]/g,"_");
    var source="var payload=JSON.parse(response.body);\n";
    source += "var candidates=[];";
    source += "var fields=[\"createdItems\",\"updatedItems\",\"deletedItems\"];fields.forEach(function(f){(payload[f]||[]).forEach(function(item){candidates.push(item);});});";
    source += "if(candidates.length!==1) pvg.fail('Create identity ambiguous; no merge guess');payload=candidates[0];\n";
    source += "if(!payload.id) pvg.fail('Create identity absent');pvg.rtv.set("+JSON.stringify("ID_"+key)+",payload.id);pvg.rtv.set("+JSON.stringify("ROUTE_"+key)+",payload["+"\"id\""+"]);\n";
    return requestRest("POST","/api/households/shopping/items",body,[201],
        {action:"create",type:"ShoppingListItemOut",logicalId:logicalId,expected:body,affected:[logicalId].concat(Object.keys(parents).map(function(k){return parents[k].id;}))},callbackFromSource(source));
}

// #/paths/~1api~1households~1shopping~1items~1{item_id}/get
function verifyShoppingListItemOut(resource) {
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    return requestRest("GET","/api/households/shopping/items/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"read",type:"ShoppingListItemOut",logicalId:resource.id},
        callbackFromSource(validationSource(resource.expected,"ID_"+key,"SNAPSHOT_"+key,null,false)));
}

// #/paths/~1api~1households~1shopping~1items~1{item_id}/put
function updateShoppingListItemOut(resource, delta) {
    var owner=resource.id+"_"+(resource.revision+1);
    request(bp.Event("ModelWriteBegin",{logicalId:resource.id,owner:owner,revision:resource.revision+1}));
    var key=resource.id.replace(/[^A-Za-z0-9_]/g,"_");
    var prepare="var before=JSON.parse(response.body);var body={};var fields="+"[\"quantity\",\"unit\",\"food\",\"referencedRecipe\",\"note\",\"display\",\"shoppingListId\",\"checked\",\"position\",\"foodId\",\"labelId\",\"unitId\",\"extras\",\"recipeReferences\"]"+";fields.forEach(function(f){if(before[f]!==undefined)body[f]=before[f];});var delta="+JSON.stringify(delta)+";";
    prepare += "function resolve(v){if(typeof v==='string'&&/^@\\{[A-Za-z0-9_]+\\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v&&typeof v==='object'){var r={};Object.keys(v).forEach(function(k){r[k]=resolve(v[k]);});return r;}return v;}";
    prepare += "Object.keys(delta).forEach(function(f){body[f]=resolve(delta[f]);});var required="+"[\"shoppingListId\"]"+";required.forEach(function(f){if(body[f]===undefined)pvg.fail('Required update carry absent: '+f);});pvg.rtv.set("+JSON.stringify("UPDATE_"+key)+",JSON.stringify(body));";
    requestRest("GET","/api/households/shopping/items/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),undefined,[200],
        {action:"prepare",type:"ShoppingListItemOut",logicalId:resource.id},callbackFromSource(validationSource(resource.expected,"ID_"+key,null,prepare)));
    return requestRest("PUT","/api/households/shopping/items/PLACEHOLDER".replace("PLACEHOLDER","@{ROUTE_"+key+"}"),"@{UPDATE_"+key+"}",[200],
        {action:"update",type:"ShoppingListItemOut",logicalId:resource.id,expected:delta,owner:owner,affected:[resource.id]},
        callbackFromSource("if(response.body) JSON.parse(response.body);"));
}

// Contribution operation and all observation HTTP stay in this shared interface.
var contributionWirePlan={"operation_path":"/api/households/shopping/lists/{item_id}/recipe","codes":[200],"recipe_type":"Recipe","list_type":"ShoppingListOut","item_type":"ShoppingListItemOut","ingredients_field":"recipeIngredient","quantity_field":"quantity","recipe_key":"recipeId","increment_field":"recipeIncrementQuantity","item_array":"listItems","item_refs":"recipeReferences","list_refs":"recipeReferences","reference_quantity":"recipeQuantity","reference_scale":"recipeScale","owner_key":"shoppingListId","child_key":"shoppingListItemId","keys":[{"source":"unit","item":"unitId"},{"source":"food","item":"foodId"}],"recipe_detail":"/api/recipes/{slug}","recipe_parameter":"slug","list_detail":"/api/households/shopping/lists/{item_id}","list_parameter":"item_id","item_detail":"/api/households/shopping/items/{item_id}","item_parameter":"item_id","sources":["#/paths/~1api~1households~1shopping~1lists~1{item_id}~1recipe/post","#/paths/~1api~1recipes~1{slug}/patch/requestBody","#/paths/~1api~1households~1shopping~1items~1{item_id}/get","#/paths/~1api~1households~1shopping~1lists~1{item_id}/get"],"inference":"summary Add; array input; source Id; numeric Increment; unique container response; schema-linked item and references","hypothesis":"shared dependency keys merge into one item; quantities add sum(source quantities)*increment; container reference quantity tracks sum(increments); item reference quantity times scale equals the DAL item quantity. This is a falsifiable generic hypothesis, not a guarantee encoded by OpenAPI.","scales":[1,0.5],"fixture_quantities":[2,4]};
function contributionCallback(expected, kind, finish) {
    var code="var plan="+JSON.stringify(contributionWirePlan)+";var expected="+JSON.stringify(expected)+";var kind="+JSON.stringify(kind)+";var finish="+finish+";";
    code+="("+validateContributionResponse.toString()+")(response,plan,expected,kind,finish);";
    return callbackFromSource(code);
}
function contributeSourceToList(recipe,list,scale,stage) {
    var previous=ctx.runQuery("Contribution.All");
    var expected=contributionExpected(recipe,list,previous.length ? previous[0].expected : null,scale);
    var body={};body[contributionWirePlan.recipe_key]=expected.recipeId;body[contributionWirePlan.increment_field]=scale;
    return requestRest("POST",contributionWirePlan.operation_path.replace("{"+contributionWirePlan.list_parameter+"}",expected.listId),[body],contributionWirePlan.codes,
        {action:"contribute",stage:stage,recipe:recipe.id,list:list.id,expected:expected,affected:[list.id]},
        contributionCallback(expected,"operation",false));
}
function readContributionItem(state) {
    // One RTV expression chooses bound item ID, or a read-only absent sentinel if discovery failed.
    var route=contributionWirePlan.item_detail.replace("{"+contributionWirePlan.item_parameter+"}","@{F01_ITEM_ID}");
    return requestRest("GET",route,undefined,[200,404],{action:"observeContributionItem"},contributionCallback(state.expected,"item",false));
}
function readContributionList(state,finish) {
    var route=contributionWirePlan.list_detail.replace("{"+contributionWirePlan.list_parameter+"}",state.expected.listId);
    return requestRest("GET",route,undefined,[200],{action:"observeContributionList"},contributionCallback(state.expected,"list",!!finish));
}
function readContributionRecipe(state) {
    var route=contributionWirePlan.recipe_detail.replace("{"+contributionWirePlan.recipe_parameter+"}","@{ROUTE_"+state.recipe+"}");
    return requestRest("GET",route,undefined,[200],{action:"observeContributionRecipe"},contributionCallback(state.expected,"recipe",false));
}

function validateContributionResponse(response,plan,expected,kind,finish) {

function resolve(v){if(typeof v==='string' && /^@\{[A-Za-z0-9_]+\}$/.test(v))return pvg.rtv.get(v.slice(2,-1));if(Array.isArray(v))return v.map(resolve);if(v && typeof v==='object'){var out={};Object.keys(v).forEach(function(k){out[k]=resolve(v[k]);});return out;}return v;}
expected=resolve(expected);
if(kind==='operation' && expected.referenceQuantity===1){pvg.rtv.set('F01_REVIEW',JSON.stringify({issues:[],receipts:[],stages:0}));pvg.rtv.set('F01_ITEM_ID','');pvg.rtv.set('F01_REF_item','');pvg.rtv.set('F01_REF_list','');}
function bound(key){return String(pvg.rtv.get(key));}
var review=JSON.parse(String(pvg.rtv.get('F01_REVIEW')));
function problem(message){review.issues.push(kind+': '+message);}
function same(actual,wanted,path){if(Array.isArray(wanted)){if(!Array.isArray(actual)||actual.length!==wanted.length){problem(path+' length');return;}wanted.forEach(function(v,i){same(actual[i],v,path+'['+i+']');});}else if(wanted && typeof wanted==='object'){if(!actual){problem(path+' absent');return;}Object.keys(wanted).forEach(function(k){same(actual[k],wanted[k],path+'.'+k);});}else if(actual!==wanted)problem(path+' expected '+JSON.stringify(wanted)+' observed '+JSON.stringify(actual));}
var observed;
try {observed=JSON.parse(response.body);}catch(e){problem('Non-JSON response');observed={};}
var receipt={kind:kind,expected:expected,response:observed};review.receipts.push(receipt);
bp.log.info('F01_RECEIPT '+JSON.stringify(receipt));
function reference(rows,label){
    var matches=(rows || []).filter(function(r){return r[plan.recipe_key]===expected.recipeId;});
    if(matches.length!==1){problem(label+' requires exactly one source reference');return;}
    if(label==='list'){same(matches[0][plan.reference_quantity],expected.referenceQuantity,label+'.quantity');}
    else{var quantity=matches[0][plan.reference_quantity],scale=matches[0][plan.reference_scale];
        if(typeof quantity!=='number' || typeof scale!=='number' || !isFinite(quantity*scale))problem('Non-numeric item reference quantity/scale');
        else same(quantity*scale,expected.quantity,'item.referenceQuantityTimesScale');}
    if(!matches[0].id)problem(label+' reference identity absent');
    var refKey='F01_REF_'+label,known=bound(refKey);
    if(known && matches[0].id!==known)problem(label+' reference identity changed');
    if(!known)pvg.rtv.set(refKey,matches[0].id);
    if(label==='item')same(matches[0][plan.child_key],bound('F01_ITEM_ID'),label+'.child');
}
function item(actual){
    if(!actual){problem('Item absent');return;}
    same(actual.id,bound('F01_ITEM_ID'),'item.id');
    same(actual[plan.quantity_field],expected.quantity,'item.quantity');
    same(actual[plan.owner_key],expected.listId,'item.owner');
    Object.keys(expected.keys).forEach(function(k){same(actual[k],expected.keys[k],'item.'+k);});
    reference(actual[plan.item_refs],'item');
}
if(kind==='operation' || kind==='list'){
    same(observed.id,expected.listId,'list.id');
    var items=observed[plan.item_array] || [];
    if(items.length!==1)problem('Expected one merged item, observed '+items.length);
    if(kind==='operation' && items.length===1 && !bound('F01_ITEM_ID'))pvg.rtv.set('F01_ITEM_ID',items[0].id);
    if(!bound('F01_ITEM_ID'))pvg.rtv.set('F01_ITEM_ID','00000000-0000-4000-8000-000000000000');
    if(items.length===1)item(items[0]);
    reference(observed[plan.list_refs],'list');
}else if(kind==='item'){item(observed);
}else if(kind==='recipe'){same(observed.id,expected.recipeId,'recipe.id');same(observed,expected.recipeExpected,'recipe');}
if(finish){review.stages++;review.status=review.issues.length ? 'F01_SEMANTIC_CANDIDATE' : 'F01_STAGE_PASS';bp.log.info('F01_EVIDENCE '+JSON.stringify(review));}
pvg.rtv.set('F01_REVIEW',JSON.stringify(review));
if(finish && review.issues.length)pvg.fail('F01 semantic discrepancy; all post-write observation requests completed. Review F01_EVIDENCE.');

}

